spring.datasource.url=${MYSQL_PROD_URL}
spring.datasource.username=${MYSQL_PROD_USERNAME}
spring.datasource.password=${MYSQL_PROD_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Si da error al acceder a las tablas de la base de datos, pasar el valor update para que cree la estructura
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# En producción no se ejecuta el data.sql por defecto
spring.sql.init.mode=never

logging.level.co.edu.sena.productsreact=INFO
logging.level.org.hibernate.SQL=WARN
