spring.datasource.url=${SQLSERVER_DEV_URL}
spring.datasource.username=${SQLSERVER_DEV_USERNAME}
spring.datasource.password=${SQLSERVER_DEV_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
