spring.datasource.url=${SQLSERVER_PROD_URL}
spring.datasource.username=${SQLSERVER_PROD_USERNAME}
spring.datasource.password=${SQLSERVER_PROD_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# Si da error al acceder a las tablas de la base de datos, pasar el valor update para que cree la estructura
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.sql.init.mode=never

logging.level.co.edu.sena.productsreact=INFO
logging.level.org.hibernate.SQL=WARN
